#include "BacktestEngine.h"

#include <iostream>


BacktestEngine::BacktestEngine()
    : portfolio(100000.0),
      latestMarketPrice(0.0),
      latestMarketTimestamp(""),
      latestSymbol(""),
      pendingOrder(nullptr) {
}


// --------------------------------------------------
// PROCESS ONE MARKET EVENT
//
// The engine processes one completed market bar at
// a time.
//
// IMPORTANT TIMING RULE:
//
// An order generated from bar t does NOT execute
// immediately.
//
// It becomes a pending order and executes when bar
// t+1 arrives, using bar t+1's OPEN price.
//
// This prevents same-bar execution / look-ahead bias.
// --------------------------------------------------

void BacktestEngine::processMarketEvent(
    const std::shared_ptr<MarketEvent>& marketEvent
) {

    // --------------------------------------------------
    // STEP 1:
    // Execute any order generated by the PREVIOUS bar.
    //
    // The current MarketEvent represents the next bar,
    // so its OPEN is our execution price.
    // --------------------------------------------------

    if (pendingOrder != nullptr) {

        double nextBarOpen =
            marketEvent->getOpen();


        // --------------------------------------------------
        // Before executing a BUY, make sure the portfolio
        // has enough cash.
        //
        // SELL orders from our current long-only strategy
        // do not require additional cash.
        // --------------------------------------------------

        if (!portfolio.canExecuteOrder(
                pendingOrder,
                nextBarOpen
            )) {

            std::cout
                << "\nORDER REJECTED - INSUFFICIENT CASH\n";

            std::cout
                << "Timestamp: "
                << marketEvent->getTimestamp()
                << '\n';

            std::cout
                << "Symbol: "
                << pendingOrder->getSymbol()
                << '\n';

            std::cout
                << "Available Cash: "
                << portfolio.getCash()
                << '\n';

            std::cout
                << "Execution Price: "
                << nextBarOpen
                << '\n';

            std::cout
                << "Quantity: "
                << pendingOrder->getQuantity()
                << '\n';

            std::cout
                << "Required Cash: "
                << nextBarOpen *
                   pendingOrder->getQuantity() +
                   1.0
                << '\n';


            // Reject and remove the pending order.

            pendingOrder = nullptr;
        }

        else {

            // --------------------------------------------------
            // Execute at the current bar's OPEN.
            //
            // IMPORTANT:
            //
            // We now explicitly pass the CURRENT market
            // timestamp to ExecutionHandler.
            //
            // Therefore the FillEvent timestamp represents
            // when execution ACTUALLY occurred rather than
            // when the order was originally generated.
            // --------------------------------------------------

            auto fillEvent =
                executionHandler.executeOrder(
                    pendingOrder,
                    nextBarOpen,
                    marketEvent->getTimestamp()
                );


            if (fillEvent != nullptr) {

                portfolio.updateFill(fillEvent);


                std::cout
                    << "\nExecuting PENDING ORDER at next bar OPEN\n";

                std::cout
                    << "Timestamp: "
                    << fillEvent->getTimestamp()
                    << '\n';

                std::cout
                    << "Symbol: "
                    << fillEvent->getSymbol()
                    << '\n';

                std::cout
                    << "Next Bar Open: "
                    << nextBarOpen
                    << '\n';

                std::cout
                    << "Quantity: "
                    << fillEvent->getQuantity()
                    << '\n';

                std::cout
                    << "Fill Price: "
                    << fillEvent->getFillPrice()
                    << '\n';

                std::cout
                    << "Commission: "
                    << fillEvent->getCommission()
                    << '\n';

                std::cout
                    << "Side: "
                    << (
                        fillEvent->getSide() ==
                        OrderSide::BUY
                            ? "BUY"
                            : "SELL"
                    )
                    << '\n';

                std::cout
                    << "Portfolio Cash: "
                    << portfolio.getCash()
                    << '\n';

                std::cout
                    << "Portfolio Position: "
                    << portfolio.getPosition()
                    << '\n';
            }


            pendingOrder = nullptr;
        }
    }


    // --------------------------------------------------
    // STEP 2:
    // Process the CURRENT market bar.
    // --------------------------------------------------

    eventQueue.push(marketEvent);

    processEventQueue();


    // --------------------------------------------------
    // STEP 3:
    // Record end-of-bar portfolio equity.
    //
    // This gives us exactly one equity observation for
    // each market bar.
    // --------------------------------------------------

    equityCurve.push_back(
        portfolio.getTotalEquity(
            latestMarketPrice
        )
    );
}


// --------------------------------------------------
// PROCESS EVENT QUEUE
//
// MARKET
//      ↓
// SIGNAL
//      ↓
// ORDER
//
// The ORDER is stored as pending rather than executed
// immediately.
// --------------------------------------------------

void BacktestEngine::processEventQueue() {

    while (!eventQueue.empty()) {

        auto event =
            eventQueue.pop();


        if (event == nullptr) {
            continue;
        }


        // --------------------------------------------------
        // MARKET EVENT
        // --------------------------------------------------

        if (event->getType() ==
            EventType::MARKET) {

            auto marketEvent =
                std::dynamic_pointer_cast<MarketEvent>(
                    event
                );


            if (marketEvent == nullptr) {
                continue;
            }


            latestMarketPrice =
                marketEvent->getClose();

            latestMarketTimestamp =
             marketEvent->getTimestamp();

            latestSymbol =
                marketEvent->getSymbol();

            std::cout
                << "\nProcessing MARKET event\n";

            std::cout
                << "Timestamp: "
                << marketEvent->getTimestamp()
                << '\n';

            std::cout
                << "Symbol: "
                << marketEvent->getSymbol()
                << '\n';

            std::cout
                << "Open: "
                << marketEvent->getOpen()
                << '\n';

            std::cout
                << "Close: "
                << marketEvent->getClose()
                << '\n';

            std::cout
                << "Volume: "
                << marketEvent->getVolume()
                << '\n';

            std::cout
                << "Portfolio Market Value: "
                << portfolio.getMarketValue(
                    latestMarketPrice
                )
                << '\n';

            std::cout
                << "Portfolio Total Equity: "
                << portfolio.getTotalEquity(
                    latestMarketPrice
                )
                << '\n';


            // Ask the strategy what it wants to do.

            auto signalEvent =
                strategy.generateSignal(
                    marketEvent
                );


            if (signalEvent != nullptr) {
                eventQueue.push(signalEvent);
            }
        }


        // --------------------------------------------------
        // SIGNAL EVENT
        // --------------------------------------------------

        else if (
            event->getType() ==
            EventType::SIGNAL
        ) {

            auto signalEvent =
                std::dynamic_pointer_cast<SignalEvent>(
                    event
                );


            if (signalEvent == nullptr) {
                continue;
            }


            std::cout
                << "\nProcessing SIGNAL event\n";

            std::cout
                << "Timestamp: "
                << signalEvent->getTimestamp()
                << '\n';

            std::cout
                << "Symbol: "
                << signalEvent->getSymbol()
                << '\n';

            std::cout
                << "Strength: "
                << signalEvent->getStrength()
                << '\n';


            if (
                signalEvent->getSignalType() ==
                SignalType::LONG
            ) {

                std::cout
                    << "Signal: LONG\n";
            }

            else if (
                signalEvent->getSignalType() ==
                SignalType::SHORT
            ) {

                std::cout
                    << "Signal: SHORT\n";
            }

            else {

                std::cout
                    << "Signal: EXIT\n";
            }


            // Convert strategy intent into an order.

            auto orderEvent =
                portfolio.generateOrder(
                    signalEvent
                );


            if (orderEvent != nullptr) {
                eventQueue.push(orderEvent);
            }
        }


        // --------------------------------------------------
        // ORDER EVENT
        // --------------------------------------------------

        else if (
            event->getType() ==
            EventType::ORDER
        ) {

            auto orderEvent =
                std::dynamic_pointer_cast<OrderEvent>(
                    event
                );


            if (orderEvent == nullptr) {
                continue;
            }


            std::cout
                << "\nProcessing ORDER event\n";

            std::cout
                << "Timestamp: "
                << orderEvent->getTimestamp()
                << '\n';

            std::cout
                << "Symbol: "
                << orderEvent->getSymbol()
                << '\n';

            std::cout
                << "Quantity: "
                << orderEvent->getQuantity()
                << '\n';


            std::cout
                << "Side: "
                << (
                    orderEvent->getSide() ==
                    OrderSide::BUY
                        ? "BUY"
                        : "SELL"
                )
                << '\n';


            std::cout
                << "Order Type: "
                << (
                    orderEvent->getOrderType() ==
                    OrderType::MARKET
                        ? "MARKET"
                        : "LIMIT"
                )
                << '\n';


            // --------------------------------------------------
            // DO NOT execute the order here.
            //
            // The order was generated using information from
            // the current completed bar.
            //
            // It must wait until the next bar arrives.
            // --------------------------------------------------

            pendingOrder =
                orderEvent;


            std::cout
                << "Order Status: "
                << "PENDING FOR NEXT BAR OPEN\n";
        }


        // --------------------------------------------------
        // FILL EVENT
        //
        // This branch remains available for FillEvents that
        // may enter the queue in future versions.
        //
        // Current next-bar execution updates the portfolio
        // directly when the pending order executes.
        // --------------------------------------------------

        else if (
            event->getType() ==
            EventType::FILL
        ) {

            auto fillEvent =
                std::dynamic_pointer_cast<FillEvent>(
                    event
                );


            if (fillEvent == nullptr) {
                continue;
            }


            portfolio.updateFill(
                fillEvent
            );


            std::cout
                << "\nProcessing FILL event\n";

            std::cout
                << "Timestamp: "
                << fillEvent->getTimestamp()
                << '\n';

            std::cout
                << "Symbol: "
                << fillEvent->getSymbol()
                << '\n';

            std::cout
                << "Quantity: "
                << fillEvent->getQuantity()
                << '\n';

            std::cout
                << "Fill Price: "
                << fillEvent->getFillPrice()
                << '\n';

            std::cout
                << "Commission: "
                << fillEvent->getCommission()
                << '\n';

            std::cout
                << "Side: "
                << (
                    fillEvent->getSide() ==
                    OrderSide::BUY
                        ? "BUY"
                        : "SELL"
                )
                << '\n';
        }
    }
}


// --------------------------------------------------
// GET EQUITY CURVE
// --------------------------------------------------

const std::vector<double>&
BacktestEngine::getEquityCurve() const {

    return equityCurve;
}


// --------------------------------------------------
// GET COMPLETED TRADES
// --------------------------------------------------

const std::vector<Trade>&
BacktestEngine::getCompletedTrades() const {

    return portfolio.getCompletedTrades();
}


// --------------------------------------------------
// GET CURRENT POSITION
// --------------------------------------------------

int BacktestEngine::getPosition() const {

    return portfolio.getPosition();
}


// --------------------------------------------------
// CLOSE OPEN POSITION AT END OF BACKTEST
// --------------------------------------------------

void BacktestEngine::closeOpenPosition() {

    // --------------------------------------------------
    // If an order was generated from the final bar,
    // there is no next bar available for execution.
    //
    // Therefore the order must be discarded.
    // --------------------------------------------------

    if (pendingOrder != nullptr) {

        std::cout
            << "\nDiscarding final pending order "
            << "(no next bar available)\n";

        pendingOrder = nullptr;
    }


    // --------------------------------------------------
    // If there is no actual filled position remaining,
    // there is nothing else to close.
    // --------------------------------------------------

    if (portfolio.getPosition() <= 0) {
        return;
    }


    // --------------------------------------------------
    // Force-liquidate any position that was already open
    // before the dataset ended.
    //
    // We currently use the final observed market price.
    // --------------------------------------------------

    auto liquidationOrder =
    std::make_shared<OrderEvent>(
        latestMarketTimestamp,
        latestSymbol,
        OrderType::MARKET,
        OrderSide::SELL,
        portfolio.getPosition()
    );


    // --------------------------------------------------
    // Because there is no next bar, the forced liquidation
    // uses the final available market price.
    //
    // For this special terminal operation we use the
    // end-of-backtest timestamp as the execution timestamp.
    // --------------------------------------------------

    auto liquidationFill =
        executionHandler.executeOrder(
            liquidationOrder,
            latestMarketPrice,
            latestMarketTimestamp
        );

    if (liquidationFill != nullptr) {

        portfolio.updateFill(
            liquidationFill
        );


        std::cout
            << "\nForced End-of-Backtest Liquidation\n";

        std::cout
            << "Fill Price: "
            << liquidationFill->getFillPrice()
            << '\n';

        std::cout
            << "Quantity: "
            << liquidationFill->getQuantity()
            << '\n';

        std::cout
            << "Commission: "
            << liquidationFill->getCommission()
            << '\n';

        std::cout
            << "Portfolio Cash: "
            << portfolio.getCash()
            << '\n';

        std::cout
            << "Portfolio Position: "
            << portfolio.getPosition()
            << '\n';
    }


    // --------------------------------------------------
    // The final equity observation already exists.
    //
    // Replace it with post-liquidation equity rather than
    // adding another observation. This preserves one equity
    // sample per market bar.
    // --------------------------------------------------

    if (!equityCurve.empty()) {

        equityCurve.back() =
            portfolio.getTotalEquity(
                latestMarketPrice
            );
    }
}