#include "Portfolio.h"


Portfolio::Portfolio(double initialCash)
    : cash(initialCash),
      position(0),
      entryTimestamp(""),
      entryPrice(0.0),
      entryCommission(0.0) {
}


std::shared_ptr<OrderEvent> Portfolio::generateOrder(
    const std::shared_ptr<SignalEvent>& signalEvent
) {
    // LONG signal while flat -> BUY 100 shares.
    if (signalEvent->getSignalType() == SignalType::LONG &&
        position == 0) {

        return std::make_shared<OrderEvent>(
            signalEvent->getTimestamp(),
            signalEvent->getSymbol(),
            OrderType::MARKET,
            OrderSide::BUY,
            100
        );
    }

    // EXIT signal while holding a position -> SELL entire position.
    if (signalEvent->getSignalType() == SignalType::EXIT &&
        position > 0) {

        return std::make_shared<OrderEvent>(
            signalEvent->getTimestamp(),
            signalEvent->getSymbol(),
            OrderType::MARKET,
            OrderSide::SELL,
            position
        );
    }

    return nullptr;
}


bool Portfolio::canExecuteOrder(
    const std::shared_ptr<OrderEvent>& orderEvent,
    double executionPrice,
    double estimatedCommission
) const {

    // --------------------------------------------------
    // SELL ORDER
    // --------------------------------------------------
    //
    // A SELL generated by our current long-only strategy
    // is closing an existing position, so it does not
    // require cash to purchase shares.
    // --------------------------------------------------

    if (orderEvent->getSide() == OrderSide::SELL) {
        return true;
    }


    // --------------------------------------------------
    // BUY ORDER
    // --------------------------------------------------

    double requiredCash =
        executionPrice *
        orderEvent->getQuantity()
        + estimatedCommission;

    return cash >= requiredCash;
}


void Portfolio::updateFill(
    const std::shared_ptr<FillEvent>& fillEvent
) {
    double transactionValue =
        fillEvent->getFillPrice() *
        fillEvent->getQuantity();


    // --------------------------------------------------
    // BUY FILL
    // --------------------------------------------------

    if (fillEvent->getSide() == OrderSide::BUY) {

        position += fillEvent->getQuantity();

        cash -= transactionValue;
        cash -= fillEvent->getCommission();

        // Remember the entry so we can construct a
        // completed Trade when the position is sold.
        entryTimestamp = fillEvent->getTimestamp();
        entryPrice = fillEvent->getFillPrice();
        entryCommission = fillEvent->getCommission();
    }


    // --------------------------------------------------
    // SELL FILL
    // --------------------------------------------------

    if (fillEvent->getSide() == OrderSide::SELL) {

        // Construct the completed round-trip trade.
        Trade completedTrade(
            fillEvent->getSymbol(),
            entryTimestamp,
            fillEvent->getTimestamp(),
            entryPrice,
            fillEvent->getFillPrice(),
            fillEvent->getQuantity(),
            entryCommission,
            fillEvent->getCommission()
        );

        // Store it in the portfolio's trade history.
        completedTrades.push_back(completedTrade);

        // Update portfolio accounting.
        position -= fillEvent->getQuantity();

        cash += transactionValue;
        cash -= fillEvent->getCommission();

        // The trade is closed, so clear the stored entry.
        entryTimestamp = "";
        entryPrice = 0.0;
        entryCommission = 0.0;
    }
}


double Portfolio::getCash() const {
    return cash;
}


int Portfolio::getPosition() const {
    return position;
}


double Portfolio::getMarketValue(double marketPrice) const {
    return position * marketPrice;
}


double Portfolio::getTotalEquity(double marketPrice) const {
    return cash + getMarketValue(marketPrice);
}


const std::vector<Trade>& Portfolio::getCompletedTrades() const {
    return completedTrades;
}